Finger peint library update
ConnectedHomes/react-native-fingerprint-scanner pull request #3
Opened 2018-08-10 15:23 UTC by vikas0309

This PR is for Reseting mFingerprintIdentify to reset to its initial value, so it again checks at the hardware level.

2018-08-14 15:42 UTC, udaisshekhawat commented on android/src/main/java/com/hieuvp/fingerprint/ReactNativeFingerprintScannerModule.java
> +     public void isFingerPrintIdentifyRefresh() {
If this function is to reset mFingerprintIdentify then please use relevant name for the function.
isFingerPrintIdentifyRefresh - Doesn't suit as per the functionality.

2018-08-14 15:43 UTC, udaisshekhawat requested changes
Please see the comments ..

2018-08-15 11:06 UTC, udaisshekhawat approved these changes
Looks good to me now ..

2018-08-15 11:11 UTC, karthiganesan90 approved these changes

2018-08-15 11:16 UTC, merged